809 team PR
Ementree/.Net-2020 pull request #24
Opened 2020-04-09 18:18 UTC by Giviruk

2020-04-12 16:18 UTC, max-arshinov requested changes

2020-04-12 16:18 UTC, max-arshinov commented on DotNet2020/DotNet2020.Domain.6/Controllers/CapacityController.cs
> +            var months = new List<string>()
Вынести в сервис, объединить с DateTimeExtensions для названия месяцев

2020-04-20 10:09 UTC, Yamaidar requested changes

2020-04-20 10:09 UTC, Yamaidar commented on DotNet2020/DotNet2020.Domain.6/Controllers/FunctionalCapacityController.cs
> +            var resourceType = _context.Set<ResourceGroupType>().ToList();
Это не используется, нужно убрать

2020-04-20 10:16 UTC, Hernantos commented on DotNet2020/DotNet2020.Domain.6/Controllers/FunctionalCapacityController.cs
> +            var resourceType = _context.Set<ResourceGroupType>().ToList();
Предварительно стягивание с бд ResourceGroupType позволяет избежать  .Include() в нескольких запросах

2020-04-20 10:19 UTC, Yamaidar commented on DotNet2020/DotNet2020.Domain.6/Controllers/FunctionalCapacityController.cs
> +            var resourceType = _context.Set<ResourceGroupType>().ToList();
Понятно
Тогда можно этот комментарий в код добавить

2020-04-20 10:55 UTC, Hernantos commented on DotNet2020/DotNet2020.Domain.6/Controllers/FunctionalCapacityController.cs
> +            var resourceType = _context.Set<ResourceGroupType>().ToList();
Хорошо, добавил

2020-04-20 11:14 UTC, merged