5
Ementree/.Net-2020 pull request #5
Opened 2020-03-19 10:35 UTC by Nesom

2020-03-25 16:26 UTC, max-arshinov requested changes
Конфликты, разрезловить

2020-03-25 16:26 UTC, max-arshinov commented on DotNet2020/DotNet2020.Domain.5/Entities/UserSkipTime.cs
> +            User = user;
Инвариант

2020-03-25 16:26 UTC, max-arshinov commented on DotNet2020/DotNet2020.Domain.5/Entities/UserSkipTime.cs
> +        public AppIdentityUser User { get; private set; }
Required?

2020-03-25 16:26 UTC, max-arshinov commented on DotNet2020/DotNet2020.Domain.5/Entities/UserWorkTime.cs
> +    public class UserWorkTime
Базовый класс?

2020-03-25 16:26 UTC, max-arshinov commented on DotNet2020/DotNet2020.Domain.5/Localization/Lang.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
Зачем это?

2020-03-25 18:04 UTC, ArtemS00 commented on DotNet2020/DotNet2020.Domain.5/Localization/Lang.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
Локализация.
Названия заголовков, полей и т.п.
Решил, что лучше будет вынести.
Если так не принято, можем удалить.

2020-03-25 18:31 UTC, ArtemS00 commented on DotNet2020/DotNet2020.Domain.5/Entities/UserSkipTime.cs
> +            User = user;
Не понял.
Необходимо убрать сеттер на юзере?
Разве в таком случае EF сможет до него дотянуться?

2020-03-25 18:37 UTC, ArtemS00 commented on DotNet2020/DotNet2020.Domain.5/Entities/UserWorkTime.cs
> +    public class UserWorkTime
Не понял.

2020-03-25 18:41 UTC, ArtemS00 commented on DotNet2020/DotNet2020.Domain.5/Entities/UserSkipTime.cs
> +        public AppIdentityUser User { get; private set; }
Добавил атрибут [Required]

2020-03-26 15:54 UTC, ArtemS00 commented on DotNet2020/DotNet2020.Domain.5/Entities/UserSkipTime.cs
> +            User = user;
Добавил проверку User на null

2020-03-26 17:45 UTC, max-arshinov approved these changes

2020-03-26 17:45 UTC, merged